### ISSUE TITLE
Worker stay alive (dedicated-mode) with node < 5.8.0

### ISSUE THREAD

**Issue by sdnetwork** [pofider/node-script-manager#14]
I have remarked that i have had a lot of process running (jsreport), so after some search, i have found the problem in 

worker-processes.js => sendAndExit

    function sendAndExit (m) {
      process.send(m, undefined, undefined, function () {
          process.exit()
      })
    }
since node 5.8 process.send have a new options arguments, so with previous version of node the callback in neither called and the fork stay alive :(

maybe this commit f460290c3d27a68a74c7296b5cfa1d671e896079 cause the problem

**Comment by bjrmatos** [comment]
ups, good catch!, the new version `0.5.11` will be included in the next version of jsreport, thnks for reporting this!

**Comment by bjrmatos** [comment]
@pofider appears that i don't have permission to publish new releases in npm, so just FYI a `npm publish` from you is needed to land the fix 😄

**Comment by pofider** [comment]
@bjrmatos Thank you, I've just gave you the permissions to npm so please publish it.

**Comment by bjrmatos** [comment]
@pofider done! thnks
