### ISSUE TITLE
remove string module dependency

### ISSUE THREAD

**Issue by dlong500** [pofider/node-script-manager#15]
Given that it appears the `string` module on npm has been abandoned, has some regex DOS security issues, and that is seems to only be used in one `index.js` file in this package, it might be best to find an alternative.

See https://github.com/jprichardson/string.js/issues/212#issuecomment-408508998

NPM is currently flagging `jsreport-core` in its security auditing due to `script-manager`'s dependency on `string`.

**Comment by pofider** [comment]
Would this satisfy you?
https://forum.jsreport.net/topic/647/redos-vulnerability-in-script-manager

**Comment by dlong500** [comment]
I do understand that there is not anything that currently appears to affect the security of jsreport in this context.  The issue is more about the spam constantly generated because of npm audit warnings.  In this particular situation, since you are only using one call to `startswith` and the minimum supported node version is now 4.x I'm pretty sure you can just use the built-in String prototype `startswith` directly and eliminate the `string` module dependency altogether.

**Comment by pofider** [comment]
Yes makes sense. Don't you want to send a PR with it? I would publish new version then.

**Comment by dlong500** [comment]
Sure, I'll do that when I can get back in town in a few days.  Thanks.

**Comment by pofider** [comment]
We removed it some time ago.
There are 0 vulnerabilities in whole jsreport currently.
